spring:
  application:
    name: company_ms
  datasource:
      url: jdbc:mariadb://localhost:3306/company_db
      username: company
      password: C0mp4ny.Ss
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /company
  port: 0