spring:
  application:
    name: company-ms
  profiles:
      active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_PATH}
  datasource:
      url: ${company-ms.datasource.url}
      username: ${company-ms.datasource.username}
      password: ${company-ms.datasource.password}
      driver-class-name: ${company-ms.datasource.driver}
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: ${company-ms.dialect}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /company
  port: 0