spring:
  application:
    name: company_ms
  datasource:
      url: jdbc:mariadb://localhost:3306/company_db
      username: company
      password: C0mp4ny.Ss
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
server:
  servlet:
    context-path: /company