version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_company
    environment:
      MYSQL_ROOT_PASSWORD: c0mp4ny.ss
      MYSQL_DATABASE: company_db
      MYSQL_USER: company
      MYSQL_PASSWORD: C0mp4ny.Ss
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local